### ISSUE TITLE
Calculating trophic levels

### ISSUE THREAD

**Issue by Thomalpas** [EcoJulia/EcologicalNetworks.jl#202]
I don't think `trophic_level` is calculating properly

If you run this code to calculate trophic levels for network 'A'

```
using EcologicalNetworks

A = [false false false false; true false false false; true true false false; false false true false]

Anet = UnipartiteNetwork(A)

trophic_level(Anet)
```

It returns:

Dict{String, Float64} with 4 entries:
  "s1" => 1.0
  "s2" => 2.0
  "s4" => 3.0
  "s3" => 2.5

However, species "s4" only consumes "s3" (trophic level 2.5) so I think should have a trophic level of 3.5 not 3.0

I am using VS Code 1.63.2 and Julia 1.7.1 on macOS Monterey 12.1

I hope this makes sense and I have provided enough information, I'm just starting my PhD and using Github and haven't opened an issue before!

**Comment by mjsmith037** [comment]
While I am not officially affiliated with this repo, let me be the first to welcome you to Github, and thank you for submitting this issue!

I think this does highlight to a bug in `trophic_level()` though maybe not the one you are thinking. Food webs are traditionally structured with links signifying that the column species consumes the row species, so, for your example, the outdegree of each species would be (note that julia scrambles the order somewhat):

```
degree(Anet, dims=1)
# Dict{String, Int64} with 4 entries:
#   "s1" => 0
#   "s2" => 1
#   "s4" => 1
#   "s3" => 2
```

and indegree:

```
degree(Anet, dims=2)
# Dict{String, Int64} with 4 entries:
#   "s1" => 2
#   "s2" => 1
#   "s4" => 0
#   "s3" => 1
```

Your issue seemed to suggest the transposed interpretation (row eating column), but even correcting for this, the trophic levels do not map correctly. Briefly, s4 should have a trophic level of 1 (0 in-degree), s3 of 2 (only eats s4), s2 of 3 (only eats s3), and s1 of 2.5 (eats s2 and s3: (2 + 3) / 2 = 2.5). Note that currently, we get the right numbers, but not assigned to the right species.

I suspect this is arising due to some confusion with axis labeling between the `degree()` function and julia internals. While julia is column major (1 = columns, 2 = rows), the degree function uses 1 for out degree (row-sums) and 2 for in degree (column-sums).

I'll dig into this particular issue with `trophic_level()` ASAP, but I think another change implicated would be inceasing degree clarity by switching the `dims` argument for degree to be a string "in"/"out" rather than an integer 1/2.

**Comment by mjsmith037** [comment]
@Thomalpas, It seems the current code stems from a translation of code in a comment on [this blog post](https://proopnarine.wordpress.com/2010/06/15/trophic-levels-for-trophic-networks/). The reason why s4 doesn't have a trophic level of 3.5 is because this approach to assigning trophic levels depends on the shortest paths from prey species to primary producers, rather than the trophic levels of those prey directly. In the case of a network structured as a tree, these are equivalent, but in your example, the shortest path from s3 to s1 (the only primary producer) is length 1 (a direct link), so the trophic level of s4 = 1 + 1/[number of prey] * sum([shortest path lengths from each prey to the closest primary producer]) = 1 + 1/1 * (1) = 2. The blog post used a trophic level of 0 to correspond to primary producers, whereas EcologicalNetworks.jl uses 1, so we add 1 to this value, getting the 3 found in your results.

Hope that makes sense!

Regarding the actual implementation in EcologicalNetworks.jl, there are a couple of issues.

The first is the transposition issue mentioned above -- this is relatively easy to fix. 

Second, the code as written uses the longest shortest path, rather than the shortest shortest path as desired (`maximum(sp[prod_id,:]...` rather than `minimum(sp[prod_id,:]...`). This is harder to fix, due the current implementation of `shortest_path()` treating 0 as both the distance from a node to itself and as a placeholder for nodes that are not connected in the network. One solution would be to update `shortest_path()` to have `missing` values for disconnected nodes:

```
function shortest_path(N::UnipartiteNetwork; nmax::Int64=50)
  # We will have a matrix of the same size at the adjacency matrix
  D = Array{Union{Missing,Int64}}(missing, size(N.edges)...)
  D[findall(!iszero, N.edges)] .= 1
  D[diagind(D)] .= 0
  for i in 2:nmax
    P = N.edges^i
    D[(P .> 0) .& sparse(ismissing.(D))] .= i
  end
  return D
end
```

This, along with updates to trophic level functions to also fix the edge direction issue:

```
function fractional_trophic_level(N::T) where {T<:UnipartiteNetwork}
  Y = nodiagonal(N)
  sp = shortest_path(Y)
  prod_id = findall(isequal(0), vec(mapslices(x -> sum(skipmissing(x)), sp, dims=1)))
  sp_to_prod = vec(mapslices(x -> minimum(skipmissing(x)), sp[prod_id,:], dims=1))
  return Dict(zip(species(Y; dims=1), sp_to_prod .+ 1))
end

function trophic_level(N::T) where {T<:UnipartiteNetwork}
  TL = fractional_trophic_level(N)
  Y = nodiagonal(N)
  D = zeros(Float64, size(Y))
  ki = degree_in(Y)
  for i in 1:richness(Y)
    if ki[species(Y)[i]] > 0.0
      D[:,i] = Y[:,i]./ki[species(Y)[i]]
    end
  end
  return Dict(zip(species(N), 1 .+ [TL[s] for s in species(Y)]' * D))
end
```

gives us the expected results, but are admittedly about 50% slower in benchmarks compared to the original formulations (mostly stemming from the changes required to include `missing` path lengths, I believe).

For comparison, consider the following (maybe not quite Minimal) Working Example:

```
A = convert(AbstractMatrix{Bool}, [0 0 1 1 1 0; 0 0 0 1 0 0; 0 0 0 0 0 1; 0 0 0 0 1 0; 0 0 0 0 0 1; 0 0 0 0 0 0]
N = UnipartiteNetwork(A))
```

We expect trophic levels of: 1, 1, 2, 2, 2.5, 3, for s1:6, respectively.
The original functions produce: 1, 1, 2, 2, 2.5, 3.5 when using  `N = UnipartiteNetwork(A'))` -- incorrectly assigning the trophic level of s6 because of the max/min bug mentioned above.

As an aside, the function "fractional_trophic_level()" seems to be inaccurately named, since it is intended to return the shortest path for each node to a primary producer, which is always an integer. Perhaps `shortest_path_to_producer()` would be more apt?

**Comment by tpoisot** [comment]
Hi @Thomalpas - thanks for the bug report! @mjsmith037 - thanks for the very thoughtful comments, this is deeply appreciated.

I'll make other comments (and changes) on #204 but I wanted to clarify a few things.

Networks in the package are *not* represented as an adjacency matrix; they are a sparse matrix (in the `edges` field of any network), with interactions going from rows to columns. Different packages use different conventions.

The fact that `dims=1` for the degree gives the out-degree comes from the fact that many users expect interactions to go from columns to rows, and so the measures assume that networks are "predator-major" for the user. This was, in retrospect, not the best decision, but it is not something that will change before an eventual `0.6` release.

The main point is: interactions shouldn't be accessed via the `edges` field - the `interactions` function (or the iterate protocol) are probably more adapted for daily use (and if they aren't, it's probably a good reason to open an issue to make them work!).

I'll follow-up on @mjsmith037 other comments on the PR for #204 - there's indeed a few :bug: lurking (and that's why the functions aren't documented yet, but I guess it's time now).
